### PR TITLE
Sol 61096: Golang Support for Partitioned Queues

### PR DESCRIPTION
**Pull request by mustafaal-sakkaf**

### CODE REVIEW

**Review by mcardy — APPROVED** [review]

**Comment by cjwmorgan-sol** [comment]
It looks like only the linux native ccsmp binaries got updated. The darwin native binaries need updating too no?

**Comment by cjwmorgan-sol** [comment]
This looks like its missing the subcode generation for the new PQ sub codes.

**Comment by mustafaal-sakkaf** [comment]
> It looks like only the linux native ccsmp binaries got updated. The darwin native binaries need updating too no?

@cjwmorgan-sol you're right. Will update the PR.

**Comment by cjwmorgan-sol** [comment]
@mustafaal-sakkaf you need the "latest" ccsmp with partitioned queue updates. That would be from the mac_m1 branch. There are instructions to follow for adding new ccsmp headers with go subcode generation from the new headers. I'll message you the instructions. The SOL-88878 branch has a commit for this.

**Review by mcardy — APPROVED** [review]

**Pull request merged**
