### PR TITLE
EBP-17: As a developer, I can access updated cache metrics

### PR DESCRIPTION
**Pull request by oodigie**
**Changes:**
- EBP-17: As a developer, I can access updated cache metrics

### CODE REVIEW

**Review by TrentDaniel — CHANGES_REQUESTED** [review]
@oodigie , implementation looks good. Please add a test for retrieving each of the three new stats to confirm that the implementation works.

**Comment by oodigie** [comment]
@TrentDaniel, I didn’t add any unit tests because we do not mock `ccsmp` metrics in the Go API. We only have unit tests for NextGenMetrics since those ones are managed within the Go API.

**Comment by TrentDaniel** [comment]
> @TrentDaniel, I didn’t add any unit tests because we do not mock `ccsmp` metrics in the Go API. We only have unit tests for NextGenMetrics since those ones are managed within the Go API.

Would it not be possible to at least assert that you can get 0 when retrieving the stats and that you don't get an error? Assuming that if the implementation was incorrect you would get an error? If  this needs to be an integration test instead of a unit test, that's fine. I'm not sure if there is an integration test module in the tests project that is intended specifically for metrics. If there is not, then you could just add these tests to the cache_test.go module int the test project.

**Comment by oodigie** [comment]
@TrentDaniel, unfortunately I tried adding a test case to assert we get 0 but it still needed to have the `ccsmp` metric mocked up so it essentially threw nil pointer panics. Testing this has to be covered by integration tests.

I am curious to know what the integration test(s) will cover at this point since we have no implementation code that affect this cache metrics? Anyways, I will add assertions to check for zero values from the cache metrics (again I would have preferred that these integration tests were added after we have actual things to test for),

**Review by TrentDaniel — APPROVED** [review]
Testing looks good, LGTM!

**Pull request merged**
